apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-mapit-app
spec:
  inputs:
    resources:
    - name: workspace-git
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://github.com/siamaksade/mapit-spring.git
  taskRef:
    kind: Task
    name: mvn-build