apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: buildah
spec:
  inputs:
    resources:
    - name: workspace-git
      targetPath: /
      type: git
    params:
    - name: dockerfile
      description: The path to the dockerfile to build
      default: ./Dockerfile
  outputs:
    resources:
    - name: image
      type: image
  steps:
  - name: build
    image: quay.io/openshift-pipeline/buildah:testing
    command:
      - buildah
    args: 
      - bud
      - --layers
      - --tls-verify=true
      - -f
      - ${inputs.params.dockerfile}
      - -t
      - ${outputs.resources.image.url}
      - .
    volumeMounts:
    - name: libcontainers
      mountPath: /var/lib/containers
  - name: push
    image: quay.io/openshift-pipeline/buildah:testing
    command:
      - buildah
    args: 
      - push
      - --tls-verify=true
      - ${outputs.resources.image.url}
    volumeMounts:
    - name: libcontainers
      mountPath: /var/lib/containers
  volumes:
    - name: libcontainers
      emptyDir: {}