apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: openshift-cli
spec:
  inputs:
    params:
    - name: command
      description: The OpenShift CLI commands to run
spec:
  steps:
    - name: run
      image: docker.io/piyushgarg/oc4-image
      command:
        - /usr/local/bin/oc
      args: 
        - ${inputs.params.command}