apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: openshift-cli
spec:
  inputs:
    params:
    - name: command
      description: The OpenShift CLI commands to run
  steps:
  - name: oc
    image: docker.io/piyushgarg/oc4-image
    command: ["/usr/local/bin/oc"]
    args:
    - "${inputs.params.command}"