apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: redeploy
spec:
  params:
    - name: DEPLOYMENT
      type: string 
    - name: IMAGE_STREAM
      type: string 
  steps:
    - name: deploy
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      script: |
        #!/usr/bin/env bash

        image_ref="image-registry.openshift-image-registry.svc:5000/$POD_NAMESPACE/$(params.IMAGE_STREAM)"

        echo "Deploying $image_ref"

        oc set image deployment/$(params.DEPLOYMENT) $(params.DEPLOYMENT)=$image_ref
        oc patch deployment $(params.DEPLOYMENT) -p "{\"spec\": {\"template\": {\"metadata\": { \"labels\": {  \"redeploy\": \"$(date +%s)\"}}}}}"
        oc rollout status deployment/$(params.DEPLOYMENT)
      env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace