---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spring-petclinic
  namespace: pipelines-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /spring-petclinic
        backend:
          serviceName: spring-petclinic
          servicePort: 8080