---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pipelines-demo
  name: admin
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - services
  - endpoints
  - pods
  - deployments
  - services
  - ingress
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-admin-binding
  namespace: pipelines-demo
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: pipelines-demo