---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: mapit-pipeline-test
spec:
  resources:
  - name: mapit-git
    type: git
  - name: mapit-image
    type: image
  tasks:
  - name: build-app
    taskRef:
      name: mvn-build
    resources:
      inputs:
      - name: workspace-git
        resource: mapit-git
      outputs:
      - name: workspace-git
        resource: mapit-git
  - name: build-image
    taskRef:
      name: buildah
    params:
    - name: dockerfile
      value: Dockerfile.openjdk
    resources:
      inputs:
      - name: workspace-git
        resource: mapit-git
        from: [build-app]
      outputs:
      - name: image
        resource: mapit-image