---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: mapit-pipeline-1
spec:
  serviceAccount: builder
  pipelineRef:
    name: mapit-pipeline
  trigger:
    type: manual
  resources:
  - name: mapit-git
    resourceRef:
      name: mapit-git
  - name: mapit-image
    resourceRef:
      name: mapit-image