# 
# USAGE:
#   oc create -f http://bit.ly/pipelines-demo
#   oc project pipelines-demo
#
#   tkn pipeline list 
#   tkn pipeline start petclinic-s2i-pipeline --resource app-git=petclinic-git --resource app-image=petclinic-image
#   tkn pipeline logs -f
# 
#   tkn pipeline start petclinic-s2i-pipeline --last
#

---
apiVersion: v1
kind: Namespace
metadata:
  name: pipelines-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline
  namespace: pipelines-demo
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pipeline-binding
  namespace: pipelines-demo
roleRef:
  kind: Role
  name: pipeline
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: pipelines-demo
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: default-admin-binding
  namespace: pipelines-demo
roleRef:
  name: admin
subjects:
- kind: ServiceAccount
  name: default
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
  namespace: pipelines-demo
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: spring-petclinic
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: spring-petclinic
    app.kubernetes.io/name: spring-petclinic
    app.kubernetes.io/part-of: spring-petclinic
    app.openshift.io/runtime: java
  name: spring-petclinic
  namespace: pipelines-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: spring-petclinic
    deploymentconfig: spring-petclinic
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: spring-petclinic
        deploymentconfig: spring-petclinic
    spec:
      containers:
      - image: spring-petclinic:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: spring-petclinic
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      containerNames:
      - spring-petclinic
      from:
        kind: ImageStreamTag
        name: spring-petclinic:latest
        namespace: pipelines-demo
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
  namespace: pipelines-demo
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: spring-petclinic
    deploymentconfig: spring-petclinic
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
  namespace: pipelines-demo
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: spring-petclinic
    weight: 100
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn-test
  namespace: pipelines-demo
spec:
  inputs:
    resources:
    - name: source
      targetPath: /
      type: git
  outputs:
    resources:
    - name: source
      targetPath: /
      type: git
  steps:
  - name: test
    image: maven:3.6.0-jdk-8-slim
    command:
    - /usr/bin/mvn
    args:
    - package
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn-verify
  namespace: pipelines-demo
spec:
  inputs:
    resources:
    - name: source
      targetPath: /
      type: git
  steps:
  - name: verify
    image: maven:3.6.0-jdk-8-slim
    command:
    - /usr/bin/mvn
    args:
    - verify
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: openshift-client
  namespace: pipelines-demo
spec:
  inputs:
    params:
      - name: ARGS
        description: The OpenShift CLI arguments to run
        default: help
  steps:
    - name: oc
      image: quay.io/openshift-pipeline/openshift-cli:0.5.0
      command: ["/usr/local/bin/oc"]
      args:
        - "${inputs.params.ARGS}"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: s2i-java-8
  namespace: pipelines-demo
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: PATH_CONTEXT
        description: The location of the path to run s2i from.
        default: .
      - name: TLSVERIFY
        description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
        default: "true"
  outputs:
    resources:
      - name: image
        type: image
  steps:
    - name: generate
      image: quay.io/openshift-pipeline/s2i
      workingdir: /workspace/source
      command: ['s2i', 'build', '${inputs.params.PATH_CONTEXT}', 'registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift', '--image-scripts-url', 'image:///usr/local/s2i', '--as-dockerfile', '/gen-source/Dockerfile.gen']
      volumeMounts:
        - name: gen-source
          mountPath: /gen-source
    - name: build
      image: quay.io/buildah/stable
      workingdir: /gen-source
      command: ['buildah', 'bud', '--tls-verify=${inputs.params.TLSVERIFY}', '--layers', '-f', '/gen-source/Dockerfile.gen', '-t', '${outputs.resources.image.url}', '.']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: gen-source
          mountPath: /gen-source
      securityContext:
        privileged: true
    - name: push
      image: quay.io/buildah/stable
      command: ['buildah', 'push', '--tls-verify=${inputs.params.TLSVERIFY}', '${outputs.resources.image.url}', 'docker://${outputs.resources.image.url}']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: gen-source
      emptyDir: {}
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kaniko
  namespace: pipelines-demo
spec:
  inputs:
    params:
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
    resources:
    - name: source
      type: git
  outputs:
    resources:
    - name: image
      type: image
  steps:
  - name: build-and-push
    workingdir: /workspace/source
    image: gcr.io/kaniko-project/executor:v0.9.0
    # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
    # https://github.com/tektoncd/pipeline/pull/706
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=${inputs.params.DOCKERFILE}
    - --context=/workspace/source/${inputs.params.CONTEXT} # The user does not need to care the workspace and the source.
    - --destination=${outputs.resources.image.url}
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: buildpacks-v3
  namespace: pipelines-demo
spec:
  inputs:
    params:
    - name: BUILDER_IMAGE
      description: The image on which builds will run (must include v3 lifecycle and compatible buildpacks).
    - name: USE_CRED_HELPERS
      description: Use Docker credential helpers for Google's GCR, Amazon's ECR, or Microsoft's ACR.
      default: 'false'
    - name: CACHE
      description: The name of the persistent app cache volume
      default: empty-dir
    - name: USER_ID
      description: The user ID of the builder image user
      default: "1000"
    - name: GROUP_ID
      description: The group ID of the builder image user
      default: "1000"

    resources:
    - name: source
      type: git

  outputs:
    resources:
    - name: image
      type: image

  steps:
  - name: prepare
    image: alpine
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args:
    - "-c"
    - >
      chown -R "${inputs.params.USER_ID}:${inputs.params.GROUP_ID}" "/builder/home" &&
      chown -R "${inputs.params.USER_ID}:${inputs.params.GROUP_ID}" "/layers" &&
      chown -R "${inputs.params.USER_ID}:${inputs.params.GROUP_ID}" "/cache" &&
      chown -R "${inputs.params.USER_ID}:${inputs.params.GROUP_ID}" "/workspace/source"
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers
    - name: "${inputs.params.CACHE}"
      mountPath: /cache

  - name: detect
    image: ${inputs.params.BUILDER_IMAGE}
    imagePullPolicy: Always
    command: ["/lifecycle/detector"]
    args:
    - "-app=/workspace/source"
    - "-group=/layers/group.toml"
    - "-plan=/layers/plan.toml"
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers
    
  - name: restore
    image: ${inputs.params.BUILDER_IMAGE}
    imagePullPolicy: Always
    command: ["/lifecycle/restorer"]
    args:
    - "-group=/layers/group.toml"
    - "-layers=/layers"
    - "-path=/cache"
    volumeMounts:
    - name: "${inputs.params.CACHE}"
      mountPath: /cache
    - name: "layers-dir"
      mountPath: /layers

  - name: analyze
    image: ${inputs.params.BUILDER_IMAGE}
    imagePullPolicy: Always
    command: ["/lifecycle/analyzer"]
    args:
    - "-layers=/layers"
    - "-helpers=${inputs.params.USE_CRED_HELPERS}"
    - "-group=/layers/group.toml"
    - "${outputs.resources.image.url}"
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers

  - name: build
    image: ${inputs.params.BUILDER_IMAGE}
    imagePullPolicy: Always
    command: ["/lifecycle/builder"]
    args:
    - "-app=/workspace/source"
    - "-layers=/layers"
    - "-group=/layers/group.toml"
    - "-plan=/layers/plan.toml"
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers

  - name: export
    image: ${inputs.params.BUILDER_IMAGE}
    imagePullPolicy: Always
    command: ["/lifecycle/exporter"]
    args:
    - "-app=/workspace/source"
    - "-layers=/layers"
    - "-helpers=${inputs.params.USE_CRED_HELPERS}"
    - "-group=/layers/group.toml"
    - "${outputs.resources.image.url}"
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers

  - name: cache
    image: ${inputs.params.BUILDER_IMAGE}
    imagePullPolicy: Always
    command: ["/lifecycle/cacher"]
    args:
    - "-layers=/layers"
    - "-group=/layers/group.toml"
    - "-path=/cache"
    volumeMounts:
    - name: "${inputs.params.CACHE}"
      mountPath: /cache
    - name: "layers-dir"
      mountPath: /layers

  volumes:
  - name: empty-dir
    emptyDir: {}
  - name: layers-dir
    emptyDir: {}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-image
  namespace: pipelines-demo
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipelines-demo/spring-petclinic
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-git
  namespace: pipelines-demo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/siamaksade/spring-petclinic
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: petclinic-s2i-pipeline
  namespace: pipelines-demo
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: unit-test
    taskRef:
      name: mvn-test
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: source
        resource: app-git
  - name: build-s2i
    taskRef:
      name: s2i-java-8
    runAfter:
      - unit-test
    params:
      - name: TLSVERIFY
        value: "false"
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image
  - name: int-test
    taskRef:
      name: mvn-verify
    runAfter:
      - unit-test
    resources:
      inputs:
      - name: source
        resource: app-git
  - name: deploy
    taskRef:
      name: openshift-client
    runAfter:
      - build-s2i
      - int-test
    params:
    - name: ARGS
      value: "rollout latest spring-petclinic"
# ---
# apiVersion: tekton.dev/v1alpha1
# kind: Pipeline
# metadata:
#   name: petclinic-kaniko-pipeline
#   namespace: pipelines-demo
# spec:
#   resources:
#   - name: app-git
#     type: git
#   - name: app-image
#     type: image
#   tasks:
#   - name: unit-test
#     taskRef:
#       name: mvn-test
#     resources:
#       inputs:
#       - name: source
#         resource: app-git
#       outputs:
#       - name: source
#         resource: app-git
#   - name: build-kaniko
#     taskRef:
#       name: kaniko
#     runAfter:
#       - unit-test
#     params:
#     - name: DOCKERFILE
#       value: ./Dockerfile.openjdk
#     resources:
#       inputs:
#       - name: source
#         resource: app-git
#         from:
#           - unit-test
#       outputs:
#       - name: image
#         resource: app-image
#   - name: int-test
#     taskRef:
#       name: mvn-verify
#     runAfter:
#       - unit-test
#     resources:
#       inputs:
#       - name: source
#         resource: app-git
#   - name: deploy
#     taskRef:
#       name: openshift-client
#     runAfter:
#       - build-kaniko
#       - int-test
#     params:
#     - name: ARGS
#       value: "rollout latest spring-petclinic"
# ---
# apiVersion: tekton.dev/v1alpha1
# kind: Pipeline
# metadata:
#   name: petclinic-buildpack-pipeline
#   namespace: pipelines-demo
# spec:
#   resources:
#   - name: app-git
#     type: git
#   - name: app-image
#     type: image
#   tasks:
#   - name: unit-test
#     taskRef:
#       name: mvn-test
#     resources:
#       inputs:
#       - name: source
#         resource: app-git
#       outputs:
#       - name: source
#         resource: app-git
#   - name: build-buildpack
#     taskRef:
#       name: buildpacks-v3
#     runAfter:
#       - unit-test
#     params:
#       - name: BUILDER_IMAGE
#         value: gcr.io/cncf-buildpacks-ci/tekton-cnb-test:bionic
#     resources:
#       inputs:
#       - name: source
#         resource: app-git
#       outputs:
#       - name: image
#         resource: app-image
#   - name: int-test
#     taskRef:
#       name: mvn-verify
#     runAfter:
#       - unit-test
#     resources:
#       inputs:
#       - name: source
#         resource: app-git
#   - name: deploy
#     taskRef:
#       name: openshift-client
#     runAfter:
#       - build-buildpack
#       - int-test
#     params:
#     - name: ARGS
#       value: "rollout latest spring-petclinic"
