apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: petclinic-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          name: github-push
      template:
        name: trigger-template-petclinic-deploy
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: petclinic-event-listener
  name: el-petclinic-event-listener
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-petclinic-event-listener
    weight: 100