apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: argocd
spec:
  destination:
    namespace: demo-stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/siamaksade/spring-petclinic-config
    targetRevision: stage
  syncPolicy:
    syncOptions:
    - Validate=false