apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pipelines-demo1

bases:
- ../base

resources:
- route.yaml
- imagestream.yaml

patchesStrategicMerge:
- pipelineresource-patch.yaml