---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mapit-spring
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: mapit-spring
  name: mapit-spring
spec:
  replicas: 1
  selector:
    app: mapit-spring
    deploymentconfig: mapit-spring
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: mapit-spring
        deploymentconfig: mapit-spring
    spec:
      containers:
      - image: ' '
        imagePullPolicy: Always
        name: mapit-spring
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      containerNames:
      - mapit-spring
      from:
        kind: ImageStreamTag
        name: mapit-spring:latest
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mapit-spring
  name: mapit-spring
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mapit-spring
    deploymentconfig: mapit-spring
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: mapit-spring
  name: mapit-spring
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: mapit-spring
    weight: 100